[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "WARPFIELD"
authors = [{name = "Jia Wei Teh", email = "jiaweiteh.astro@gmail.com"}]
dynamic = ["version", "description"]
